name: raahsetu
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  firebase_database: ^12.0.2
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.4.2
  google_maps_flutter: ^2.13.1
  flutter_geofire: ^2.0.6
  geolocator: ^14.0.2
  provider: ^6.1.5+1
  google_sign_in: ^7.2.0
  flutter_sms: ^2.3.3
  url_launcher: ^6.3.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
