// lib/firebase_options.dart
// NOTE: This is a placeholder file! It only allows the app to compile.
// The actual contents of this file are generated by 'flutterfire configure'.
// Since that command failed, we are providing a dummy file.

import 'package:firebase_core/firebase_core.dart';

// The actual Firebase options are loaded from google-services.json on Android.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for the current platform. '
            'They should be auto-generated by running the FlutterFire CLI command: '
            'flutterfire configure.'
    );
  }
}