// lib/main.dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file is generated by 'flutterfire configure'

void main() async {
  // Required to ensure Firebase can be initialized before runApp
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the generated options
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const RaahSetuApp());
}

class RaahSetuApp extends StatelessWidget {
  const RaahSetuApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'RaahSetu',
      theme: ThemeData(
        primarySwatch: Colors.deepPurple,
        useMaterial3: true,
      ),
      home: const LandingScreen(), // The first screen shown after initialization
    );
  }
}

class LandingScreen extends StatelessWidget {
  const LandingScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('RaahSetu (Setup Complete)'),
      ),
      body: Center(
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Text('Firebase initialized successfully!'),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: () {
                // Placeholder: Next step will be the Authentication flow
                ScaffoldMessenger.of(context).showSnackBar(
                  const SnackBar(content: Text('Proceeding to Authentication...')),
                );
              },
              child: const Text('Proceed to Auth'),
            ),
          ],
        ),
      ),
    );
  }
}